package model;
// Generated 07/07/2017 04:04:23 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name="Cliente"
    ,catalog="bancario"
)
public class Cliente  implements java.io.Serializable {


     private String idCliente;
     private String nombre;
     private String apellido;
     private String direccion;
     private String correo;
     private String contrasenia;
     private Set cuentas = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String idCliente, String nombre, String apellido, String direccion, String contrasenia) {
        this.idCliente = idCliente;
        this.nombre = nombre;
        this.apellido = apellido;
        this.direccion = direccion;
        this.contrasenia = contrasenia;
    }
    public Cliente(String idCliente, String nombre, String apellido, String direccion, String correo, String contrasenia, Set cuentas) {
       this.idCliente = idCliente;
       this.nombre = nombre;
       this.apellido = apellido;
       this.direccion = direccion;
       this.correo = correo;
       this.contrasenia = contrasenia;
       this.cuentas = cuentas;
    }
   
     @Id 

    
    @Column(name="idCliente", unique=true, nullable=false, length=10)
    public String getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(String idCliente) {
        this.idCliente = idCliente;
    }

    
    @Column(name="Nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="Apellido", nullable=false, length=45)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="Direccion", nullable=false, length=45)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="Correo", length=45)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }

    
    @Column(name="contrasenia", nullable=false, length=10)
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cliente")
    public Set getCuentas() {
        return this.cuentas;
    }
    
    public void setCuentas(Set cuentas) {
        this.cuentas = cuentas;
    }




}


