package model;
// Generated 07/07/2017 04:04:23 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cuenta generated by hbm2java
 */
@Entity
@Table(name="Cuenta"
    ,catalog="bancario"
)
public class Cuenta  implements java.io.Serializable {


     private String idCuenta;
     private Cliente cliente;
     private Double saldo;
     private Set servicioses = new HashSet(0);
     private Set historials = new HashSet(0);

    public Cuenta() {
    }

	
    public Cuenta(String idCuenta, Cliente cliente) {
        this.idCuenta = idCuenta;
        this.cliente = cliente;
    }
    public Cuenta(String idCuenta, Cliente cliente, Double saldo, Set servicioses, Set historials) {
       this.idCuenta = idCuenta;
       this.cliente = cliente;
       this.saldo = saldo;
       this.servicioses = servicioses;
       this.historials = historials;
    }
   
     @Id 

    
    @Column(name="idCuenta", unique=true, nullable=false, length=6)
    public String getIdCuenta() {
        return this.idCuenta;
    }
    
    public void setIdCuenta(String idCuenta) {
        this.idCuenta = idCuenta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Cliente_idCliente", nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    
    @Column(name="Saldo", precision=22, scale=0)
    public Double getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(Double saldo) {
        this.saldo = saldo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cuenta")
    public Set getServicioses() {
        return this.servicioses;
    }
    
    public void setServicioses(Set servicioses) {
        this.servicioses = servicioses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cuenta")
    public Set getHistorials() {
        return this.historials;
    }
    
    public void setHistorials(Set historials) {
        this.historials = historials;
    }




}


