package model;
// Generated 07/07/2017 04:04:23 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Servicios generated by hbm2java
 */
@Entity
@Table(name="Servicios"
    ,catalog="bancario"
)
public class Servicios  implements java.io.Serializable {


     private Integer idServicios;
     private Cuenta cuenta;
     private TipoServicio tipoServicio;
     private Double montoPagar;

    public Servicios() {
    }

	
    public Servicios(Cuenta cuenta, TipoServicio tipoServicio) {
        this.cuenta = cuenta;
        this.tipoServicio = tipoServicio;
    }
    public Servicios(Cuenta cuenta, TipoServicio tipoServicio, Double montoPagar) {
       this.cuenta = cuenta;
       this.tipoServicio = tipoServicio;
       this.montoPagar = montoPagar;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idServicios", unique=true, nullable=false)
    public Integer getIdServicios() {
        return this.idServicios;
    }
    
    public void setIdServicios(Integer idServicios) {
        this.idServicios = idServicios;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Cuenta_idCuenta", nullable=false)
    public Cuenta getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(Cuenta cuenta) {
        this.cuenta = cuenta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tipo_servicio_idtipo_servicio", nullable=false)
    public TipoServicio getTipoServicio() {
        return this.tipoServicio;
    }
    
    public void setTipoServicio(TipoServicio tipoServicio) {
        this.tipoServicio = tipoServicio;
    }

    
    @Column(name="monto_pagar", precision=22, scale=0)
    public Double getMontoPagar() {
        return this.montoPagar;
    }
    
    public void setMontoPagar(Double montoPagar) {
        this.montoPagar = montoPagar;
    }




}


