package model;
// Generated 07/07/2017 04:04:23 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoServicio generated by hbm2java
 */
@Entity
@Table(name="tipo_servicio"
    ,catalog="bancario"
)
public class TipoServicio  implements java.io.Serializable {


     private int idtipoServicio;
     private String descripcion;
     private Set servicioses = new HashSet(0);

    public TipoServicio() {
    }

	
    public TipoServicio(int idtipoServicio, String descripcion) {
        this.idtipoServicio = idtipoServicio;
        this.descripcion = descripcion;
    }
    public TipoServicio(int idtipoServicio, String descripcion, Set servicioses) {
       this.idtipoServicio = idtipoServicio;
       this.descripcion = descripcion;
       this.servicioses = servicioses;
    }
   
     @Id 

    
    @Column(name="idtipo_servicio", unique=true, nullable=false)
    public int getIdtipoServicio() {
        return this.idtipoServicio;
    }
    
    public void setIdtipoServicio(int idtipoServicio) {
        this.idtipoServicio = idtipoServicio;
    }

    
    @Column(name="descripcion", nullable=false, length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoServicio")
    public Set getServicioses() {
        return this.servicioses;
    }
    
    public void setServicioses(Set servicioses) {
        this.servicioses = servicioses;
    }




}


